# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f392b5ad7bdf7c062342a518ca1d2b53a767c0993cbb1c4f932cc7109ab6b6f6eb29fa78a9a2341c74aa5a5f2aa3a4aaca9dcfb4457ca67701dc2cd53a9fb668

test:
  secret_key_base: 5810357180315c54ccf0ee0f2e3b14a47b623b4502c36af9b913f7d681b091f9dc59e4038b9939fa1befe6a8d5be11f4faec9e2dc382589f586b88264e5ac7ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
